// Generated by CoffeeScript 1.8.0
(function() {
  var PluginError, async, gutil, through, tvm;

  async = require('async');

  through = require('through2');

  gutil = require('gulp-util');

  tvm = require('tvm');

  PluginError = gutil.PluginError;

  module.exports = (function(_this) {
    return function(opt) {
      var func, stream;
      func = function(file, enc, callback) {
        var version;
        opt = opt || {};
        version = opt.version || 'latest';
        console.log("Yo: " + version);
        return async.waterfall(function(_callback) {
          return tvm.install(version, _callback);
        }, function(_callback) {
          return tvm.use(version, _callback);
        }, function() {
          var data, str;
          if (file.isBuffer()) {
            str = file.contents.toString('utf8');
            data = tvm.tsc(str);
            file.contents = new Buffer(data);
          }
          if (file.isStream()) {
            file.contents = file.contens.pipe(tvm.tsc(file.contents));
            _this.push(file);
          }
          return callback();
        });
      };
      stream = through.obj(func);
      return stream;
    };
  })(this);

}).call(this);
